# Basic

In [ ]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
arr.ndim

2

In [ ]:
arr.shape

(4, 3)

In [ ]:
arr.size

12

In [ ]:
arr.dtype

dtype('<U21')

In [ ]:
arr.itemsize

84

In [ ]:
arr.data

# Printing arrays

In [ ]:
print(np.arange(10000).reshape(100,100)) #NumPy automatically skips the central part of the array and only prints the corners

[[   0    1    2 ...   97   98   99]
 [ 100  101  102 ...  197  198  199]
 [ 200  201  202 ...  297  298  299]
 ...
 [9700 9701 9702 ... 9797 9798 9799]
 [9800 9801 9802 ... 9897 9898 9899]
 [9900 9901 9902 ... 9997 9998 9999]]


# Array Creation & Basic operations

In [ ]:
arr2=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]],dtype=float)
arr2

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.]])

In [ ]:
arr3=arr+arr2
arr3

array([[ 2.,  4.,  6.],
       [ 8., 10., 12.],
       [14., 16., 18.],
       [20., 22., 24.]])

In [ ]:
arr4=arr3*arr
arr4

array([[  2.,   8.,  18.],
       [ 32.,  50.,  72.],
       [ 98., 128., 162.],
       [200., 242., 288.]])

In [ ]:
arr5=arr**2
arr5

array([[  1,   4,   9],
       [ 16,  25,  36],
       [ 49,  64,  81],
       [100, 121, 144]])

In [ ]:
arr5 <50

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True, False, False],
       [False, False, False]])

In [ ]:
np.sin(arr)

array([[ 0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ],
       [ 0.6569866 ,  0.98935825,  0.41211849],
       [-0.54402111, -0.99999021, -0.53657292]])

In [ ]:
arr6=arr**arr2  # arr power arr2
np.floor(arr6)

array([[1.00000000e+00, 4.00000000e+00, 2.70000000e+01],
       [2.56000000e+02, 3.12500000e+03, 4.66560000e+04],
       [8.23543000e+05, 1.67772160e+07, 3.87420489e+08],
       [1.00000000e+10, 2.85311671e+11, 8.91610045e+12]])

In [ ]:
npArr=np.zeros((3,4))  #(row,column)
npArr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
npArr2=np.ones((4,3))   #np.ones_like(npArr) shape of npArr
npArr2

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
npArr3=np.floor(np.random.rand(4,3)*10)
npArr3

array([[1., 6., 1.],
       [6., 8., 0.],
       [8., 6., 9.],
       [2., 3., 6.]])

In [ ]:
npArr4=np.arange(4,23,3) #for arange np.arange(start,stop,step) stop in not included
npArr4

array([ 4,  7, 10, 13, 16, 19, 22])

In [ ]:
npArr5=np.arange(8)           #1d array
npArr5

array([0, 1, 2, 3, 4, 5, 6, 7])

In [ ]:
npArr7=np.arange(15).reshape(3,5) #2d array
npArr7

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
npArr8=np.arange(24).reshape(4,3,2) #3d array
npArr8

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]]])

In [ ]:
npArr6=np.linspace(3,7,6)  # linespace(startpoint, endpoint, numOfDivision)
npArr6

array([3. , 3.8, 4.6, 5.4, 6.2, 7. ])

In [ ]:
A=np.array([[1,2],[3,4]])
B=np.array([[2,4],[6,8]])
print("sum:")
print(A+B)
print("sub:")
print(A-B)
print("multi:")   #elementwise product
print(A*B)
print("Division:")
print(A/B)


sum:
[[ 3  6]
 [ 9 12]]
sub:
[[-1 -2]
 [-3 -4]]
multi:
[[ 2  8]
 [18 32]]
Division:
[[0.5 0.5]
 [0.5 0.5]]


In [ ]:
A@B #matix product

array([[14, 20],
       [30, 44]])

In [ ]:
A.dot(B)  # another matrix product

array([[14, 20],
       [30, 44]])

Part 2

In [ ]:
arr1=np.arange(12).reshape(3,4)
arr1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
print(arr1.sum())     #axis=0 -> column
print(arr1.min())     #axis=1 -> row
print(arr1.max())

print(arr1.sum(axis=0)) # column wise sum
print()
print(arr1.sum(axis=1)) #row wise sum
print()
print(arr1.mean(axis=1))

66
0
11
[12 15 18 21]

[ 6 22 38]

[1.5 5.5 9.5]


Indexing, slicing and iterating

In [ ]:
a = np.arange(10)**4
a

array([   0,    1,   16,   81,  256,  625, 1296, 2401, 4096, 6561])

In [ ]:
a[2:5]

array([ 16,  81, 256])

In [ ]:
a[1:6:2]

array([  1,  81, 625])

In [ ]:
b= np.arange(15).reshape(3,5)
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
print(b[1, 1])
print(b[0:2, 1])
print(b[ : ,1])
print(b[1:3, : ]) # 3 is the stop position not included

6
[1 6]
[ 1  6 11]
[[ 5  6  7  8  9]
 [10 11 12 13 14]]


In [ ]:
b[1,1:3]

array([6, 7])

In [ ]:
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
#b.reshape(3,5)           # reshape function returns its argument with a modified shape, but resize method modifies the array itself
b.resize(5,3)
b

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

part3

In [ ]:
c=a.copy()
c

array([   0,    1,   16,   81,  256,  625, 1296, 2401, 4096, 6561])

In [ ]:
print(np.hstack((a,c)))
print()
print(np.vstack((a,c)))

[   0    1   16   81  256  625 1296 2401 4096 6561    0    1   16   81
  256  625 1296 2401 4096 6561]

[[   0    1   16   81  256  625 1296 2401 4096 6561]
 [   0    1   16   81  256  625 1296 2401 4096 6561]]


In [ ]:
c[3]=78

In [ ]:
np.column_stack((a, c))

array([[   0,    0],
       [   1,    1],
       [  16,   16],
       [  81,   78],
       [ 256,  256],
       [ 625,  625],
       [1296, 1296],
       [2401, 2401],
       [4096, 4096],
       [6561, 6561]])

Part 4

In [ ]:
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
b.var()

np.float64(18.666666666666668)

In [ ]:
b.std()

np.float64(4.320493798938574)

In [ ]:
b.max()

np.int64(14)

In [ ]:
b.mean()

np.float64(7.0)

In [ ]:
np.median(b)

np.float64(7.0)

In [ ]:
b.sum(axis=0)

array([15, 18, 21, 24, 27])

In [ ]:
b.sum(axis=1)

array([10, 35, 60])

In [ ]:
b.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
b.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])